name: Selenium WebDriver CI

on: 
  push:
    branches: 
      = main #
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .Net 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: dotnet restore SeleniumBasicExercise.sln   

      - name: Build 
        run: dotnet build --no-restore

      - name: Run testProject1
        run: dotnet test ./TestProject1/TestProject1.csproj --verbosity normal

      - name: Run testProject2
        run: dotnet test ./TestProject2/TestProject2.csproj --verbosity normal